# Generated by Django 6.0.2 on 2026-02-24 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent_module', '0001_initial'),
        ('client_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentnote',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'role': 'AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='agent_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentnote',
            name='client',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'CLIENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_about_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentnote',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_notes', to='client_module.order'),
        ),
    ]
