# Generated by Django 6.0.2 on 2026-02-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix promotionnel (optionnel)', max_digits=10, null=True),
        ),
    ]
