# Generated by Django 6.0.2 on 2026-02-24 18:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cart_items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente de paiement'), ('PAYE', 'Payé'), ('PREPARATION', 'En préparation'), ('EXPEDIE', 'Expédié'), ('EN_TRANSIT', 'En transit'), ('LIVRE', 'Livré'), ('PROBLEME', 'Problème'), ('ANNULE', 'Annulé'), ('RETOURNE', 'Retourné')], default='EN_ATTENTE', max_length=20)),
                ('total_amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('total_amount_local', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_address', models.TextField()),
                ('delivery_city', models.CharField(max_length=100)),
                ('delivery_phone', models.CharField(max_length=20)),
                ('customer_notes', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('VIREMENT', 'Virement Bancaire'), ('CASH', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money')], max_length=20)),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente de vérification'), ('CONFIRME', 'Confirmé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('transaction_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quote_amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('quote_amount_local', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('delivery_time_days', models.PositiveIntegerField(help_text='Délai de livraison en jours')),
                ('valid_until', models.DateField(help_text="Date d'expiration du devis")),
                ('quote_document', models.FileField(blank=True, null=True, upload_to='quotes/')),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourcingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_code', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sourcing/')),
                ('reference_url', models.URLField(blank=True, help_text='Lien Alibaba, Taobao, etc.', null=True)),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours de recherche'), ('DEVIS_ENVOYE', 'Devis envoyé'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('estimated_delivery_days', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sourcing_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
